name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: |
        npm install -g newman
        npm install
    - name: Building the project
      run: npm run build
    - name: Unit tests
      run: npm run test
    - name: Integration Tests
      run: npm run test:integration
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install Locust
      run: python3 -m pip install locustio
    - name: Load tests
      run: npm run test:load
